# "org" ensures this Service is used with the correct Serverless Framework Access Key.
# org: yaash
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
# app: lead-survey-app
service: lead-survey-backend-endpoint-${env:SURVEY_TYPE}

custom:
  surveyType: ${env:SURVEY_TYPE}

build:
  esbuild:
    bundle: true
    minify: true
    # sourcemap: true
    external: ["@sparticuz/chromium"]
    loader:
      '.html': 'text'   # Load HTML
      '.svg': 'text'    # Load svg
      '.css': 'text'    # Load CSS 

package:
  individually: false
  excludeDevDependencies: true
  exclude:
    - node_modules/aws-sdk/**
    - node_modules/**/.bin/**      # (optional) remove any CLI bin folders
    - .git/**                      # (optional) remove your git folder
    - docs/**                      # (optional) docs or tests if you have them

provider:
  name: aws
  runtime: nodejs20.x
  stage: ${opt:stage, 'dev'}
  region: "ap-southeast-2"
  environment:
    DYNAMODB_TABLE: ${self:service}-${self:provider.stage}
    NODE_ENV: ${self:provider.stage}
    API_BASE_URL: ${opt:stage, 'dev'}-api.example.com
    S3_BUCKET: ${self:service}-${self:provider.stage}
    SURVEY_TYPE: ${env:SURVEY_TYPE}

  iam:
    role:
      name: ${self:service}-${self:provider.stage}-CloudFormationRole

  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:PutItem
      Resource: "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.DYNAMODB_TABLE}"
    - Effect: Allow
      Action:
        - dynamodb:GetItem
      Resource: "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.DYNAMODB_TABLE}"
    - Effect: Allow
      Action:
        - dynamodb:Scan
      Resource: "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.DYNAMODB_TABLE}"
    - Effect: Allow
      Action:
        - s3:PutObject
      Resource: "arn:aws:s3:::${self:provider.environment.S3_BUCKET}/*"
      

plugins:
  - serverless-offline

stages:
  default:
    S3_BUCKET: ${self:provider.environment.S3_BUCKET}

resources:
  Resources:
    ItemsTable:
      Type: "AWS::DynamoDB::Table"
      Properties:
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        TableName: ${self:provider.environment.DYNAMODB_TABLE}
    ReportsBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:provider.environment.S3_BUCKET}
        PublicAccessBlockConfiguration:
          BlockPublicAcls: false
          BlockPublicPolicy: false
          IgnorePublicAcls: false
          RestrictPublicBuckets: false
    ReportsBucketPolicy:
      Type: AWS::S3::BucketPolicy
      Properties:
        Bucket: !Ref ReportsBucket
        PolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Principal: "*"
              Action:
                - s3:GetObject
              Resource: arn:aws:s3:::${self:provider.environment.S3_BUCKET}/*

functions:
  ping:
    handler: src/handlers/ping/ping.handler
    events:
      - http:
          path: ping
          method: get
          cors:
            origin: "*"
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
            allowCredentials: false
  generate-report:
    handler: src/handlers/report/generate-report.handler
    memorySize: 1024 # Minimum recommended
    timeout: 30 # Increase this as needed
    package:
      include:
        - src/handlers/report/templates/**
    events:
      - http:
          path: generate-report
          method: post
          cors:
            origin: "*"
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
              - access-control-allow-headers
              - access-control-allow-methods
              - access-control-allow-origin
            allowCredentials: false
  get-survey-data:
    handler: src/handlers/get-survey-data/get-survey-data.handler
    memorySize: 1024 # Minimum recommended
    timeout: 30 # Increase this as needed
    events:
      - http:
          path: get-survey-data
          method: get
          cors:
            origin: "*"
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
            allowCredentials: false
  send-consent-form:
    handler: src/handlers/send-consent-form/send-consent-form.handler
    memorySize: 1024 # Minimum recommended
    timeout: 30 # Increase this as needed
    events:
      - http:
          path: send-consent-form
          method: post
          cors:
            origin: "*"
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
            allowCredentials: false
